export const CREATE_MILESTONE_SUCCESS = "CREATE_MILESTONE_SUCCESS";
export const CREATE_MILESTONE_FAILURE = "CREATE_MILESTONE_FAILURE";

export const DELETE_MILESTONE_SUCCESS = "DELETE_MILESTONE_SUCCESS";
export const DELETE_MILESTONE_FAILURE = "DELETE_MILESTONE_FAILURE";