export const CREATE_MILESTONE_SUCCESS = "CREATE_MILESTONE_SUCCESS";
export const CREATE_MILESTONE_FAILURE = "CREATE_MILESTONE_FAILURE";

export const EDIT_MILESTONE_SUCCESS = "EDIT_MILESTONE_SUCCESS";
export const EDIT_MILESTONE_FAILURE = "EDIT_MILESTONE_FAILURE";

export const DELETE_MILESTONE_SUCCESS = "DELETE_MILESTONE_SUCCESS";
export const DELETE_MILESTONE_FAILURE = "DELETE_MILESTONE_FAILURE";

export const GET_MILESTONE_REQUEST = "GET_MILESTONE_REQUEST";
export const GET_MILESTONE_SUCCESS = "GET_MILESTONE_SUCCESS";
export const GET_MILESTONE_FAILURE = "GET_MILESTONE_FAILURE";