export const GET_PROJECT_REQUEST = "GET_PROJECT_REQUEST";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE";

export const GET_PROJECTS_BY_USER_REQUEST = "GET_PROJECTS_BY_USER_REQUEST";
export const GET_PROJECTS_BY_USER_SUCCESS = "GET_PROJECTS_BY_USER_SUCCESS";
export const GET_PROJECTS_BY_USER_FAILURE = "GET_PROJECTS_BY_USER_FAILURE";

export const GET_ALL_PROJECTS_USER_REQUEST = "GET_ALL_PROJECTS_USER_REQUEST";
export const GET_ALL_PROJECTS_USER_SUCCESS = "GET_ALL_PROJECTS_USER_SUCCESS";
export const GET_ALL_PROJECTS_USER_FAILURE = "GET_ALL_PROJECTS_USER_FAILURE";

export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILURE = "CREATE_PROJECT_FAILURE";

export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE";

export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILURE";

export const GET_ACTIVITY_REQUEST = "GET_ACTIVITY_REQUEST";
export const GET_ACTIVITY_SUCCESS = "GET_ACTIVITY_SUCCESS";
export const GET_ACTIVITY_FAILURE = "GET_ACTIVITY_FAILURE";

export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_ROLES_FAILURE = "GET_ROLES_FAILURE";

export const GET_TEAM_SUCCESS = "GET_TEAM_SUCCESS";
export const GET_TEAM_FAILURE = "GET_TEAM_FAILURE";

export const INVITATION_REQUEST = "INVITATION_REQUEST";
export const INVITATION_SUCCESS = "INVITATION_SUCCESS";
export const INVITATION_FAILURE = "INVITATION_FAILURE";

export const DELETE_INVITATION_REQUEST = "DELETE_INVITATION_REQUEST"
export const DELETE_INVITATION_SUCCESS = "DELETE_INVITATION_SUCCESS"
export const DELETE_INVITATION_FAILURE = "DELETE_INVITATION_FAILURE"

export const GET_INVITATIONS_SUCCESS = "GET_INVITATIONS_SUCCESS";
export const GET_INVITATIONS_FAILURE = "GET_INVITATIONS_FAILURE";

export const REMOVE_FROM_TEAM_SUCCESS = "REMOVE_FROM_TEAM_SUCCESS"
export const REMOVE_FROM_TEAM_FAILURE = "REMOVE_FROM_TEAM_FAILURE"

