export const GET_PROJECTS_BY_USER_REQUEST = "GET_PROJECTS_BY_USER_REQUEST";
export const GET_PROJECTS_BY_USER_SUCCESS = "GET_PROJECTS_BY_USER_SUCCESS";
export const GET_PROJECTS_BY_USER_FAILURE = "GET_PROJECTS_BY_USER_FAILURE";

export const GET_ALL_PROJECTS_USER_REQUEST = "GET_ALL_PROJECTS_USER_REQUEST";
export const GET_ALL_PROJECTS_USER_SUCCESS = "GET_ALL_PROJECTS_USER_SUCCESS";
export const GET_ALL_PROJECTS_USER_FAILURE = "GET_ALL_PROJECTS_USER_FAILURE";