export const GET_ALL_TICKETS_USER_REQUEST = "GET_ALL_TICKETS_USER_REQUEST";
export const GET_ALL_TICKETS_USER_SUCCESS = "GET_ALL_TICKETS_USER_SUCCESS";
export const GET_ALL_TICKETS_USER_FAILURE = "GET_ALL_TICKETS_USER_FAILURE";