export const GET_ALL_TICKETS_USER_REQUEST = "GET_ALL_TICKETS_USER_REQUEST";
export const GET_ALL_TICKETS_USER_SUCCESS = "GET_ALL_TICKETS_USER_SUCCESS";
export const GET_ALL_TICKETS_USER_FAILURE = "GET_ALL_TICKETS_USER_FAILURE";

export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_FAILURE = "CREATE_TICKET_FAILURE";

export const UPDATE_TICKET_SUCCESS = "UPDATE_TICKET_SUCCESS";
export const UPDATE_TICKET_FAILURE = "UPDATE_TICKET_FAILURE";

export const DELETE_TICKET_SUCCESS = "DELETE_TICKET_SUCCESS";
export const DELETE_TICKET_FAILURE = "DELETE_TICKET_FAILURE";

export const GET_TICKET_TYPES_REQUEST = "GET_TICKET_TYPES_REQUEST";
export const GET_TICKET_TYPES_SUCCESS = "GET_TICKET_TYPES_SUCCESS";
export const GET_TICKET_TYPES_FAILURE = "GET_TICKET_TYPES_FAILURE";

export const GET_TICKET_STATUS_REQUEST = "GET_TICKET_STATUS_REQUEST";
export const GET_TICKET_STATUS_SUCCESS = "GET_TICKET_STATUS_SUCCESS";
export const GET_TICKET_STATUS_FAILURE = "GET_TICKET_STATUS_FAILURE";

export const GET_TICKET_REQUEST = "GET_TICKET_REQUEST";
export const GET_TICKET_SUCCESS = "GET_TICKET_SUCCESS";
export const GET_TICKET_FAILURE = "GET_TICKET_FAILURE";
